### ISSUE TITLE
Readme is incorrect?

### ISSUE THREAD

**Issue by beyond-code-github** [fsprojects/FSharp.Interop.Dynamic#2]
In the readme.md it states that we should use

```
open FSharp.Dynamic
```

After installing the latest version from nuget it seems we now need to use the following instead?

```
open EkonBenefits.FSharp.Dynamic
```

**Comment by jbtule** [comment]
Yes, when this module moved to FSProjects, I removed 'EkonBenefits" from the name space in source, but haven't put a new build out on nuget. The fsharp foundation wants me to change the namespace to `FSharp.Interop.Dynamic`, So that's what it will end up being, So v2 is FSharp.Dynamic, and will probably only exist in source at this point and v3 will be FSharp.Interop.Dynamic, I'll try and put it in nuget soonish.

**Comment by jbtule** [comment]
Sorry, it sat so long. nuget updated.

**Comment by beyond-code-github** [comment]
:+1:
